Favorites Aaron
Lambda-School-Labs/PT17_merchant-marketplace-c-be pull request #11
Opened 2021-04-13 01:24 UTC by maxwes13

Made a favorites router that will get, post, and delete the favorite categories for the buyer's profile.
Complete, tested, ready to review and merge.
Tested with Postman.
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 My code has been reviewed by at least one peer
 My changes generate no new warnings
 New and existing unit tests pass locally with my changes
 There are no merge conflicts

2021-04-13 01:55 UTC, Brodt7258 requested changes

2021-04-13 01:55 UTC, Brodt7258 commented on api/profile/favoritesRouter.js
> +  Model.favorites('favorite_category', id)
looks like there's a signature mismatch between here and the function definition in global model, that function only accepts an id param, not a table name. Is it working correctly like this? seems likely to cause the query to always return no results.

2021-04-14 01:27 UTC, jonathan-portillo approved these changes
Looks solid!

2021-04-14 03:00 UTC, karapeoples approved these changes
You code appears to do everything it needs too...like how you made sure req params comes in as a string since I know we have to have one as the id

2021-04-15 01:08 UTC, Brodt7258 approved these changes

2021-04-15 01:11 UTC, merged